<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to Cart_1</name>
   <tag></tag>
   <elementGuidId>9093d12b-b3d7-4972-85cb-f0ca3dbaf91d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='exportsUndeliverable-cart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exportsUndeliverable-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f2f0d311-b23d-4dc2-ade3-165ef60317c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exportsUndeliverable-cart</value>
      <webElementGuid>8f2f019e-397c-4f51-b2a6-7d602236d6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-disabled a-button-span12 a-button-primary a-button-icon</value>
      <webElementGuid>d9b91627-b8bd-4851-8725-0ec1e005d799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add to Cart </value>
      <webElementGuid>3e281a68-ac00-443f-8604-135de5ab41ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exportsUndeliverable-cart&quot;)</value>
      <webElementGuid>832e51c1-4365-48c2-b8da-f926b2aa4502</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='exportsUndeliverable-cart']</value>
      <webElementGuid>60313ede-da3b-495c-aefc-2f5695bea78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='exportsUndeliverable-popover']/span</value>
      <webElementGuid>1f806a51-eed2-47a8-be25-d8efe7f5f428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[3]/following::span[7]</value>
      <webElementGuid>64015828-4bf6-4880-ba69-ccbefcf743a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IN'])[1]/following::span[7]</value>
      <webElementGuid>c3232e6d-a641-49c4-b091-29c04e4733b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Enhancements you chose aren', &quot;'&quot;, 't available for this seller.')])[1]/preceding::span[3]</value>
      <webElementGuid>87fde79a-3416-4064-ba4b-afb28660946a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To add the following enhancements to your purchase, choose a different seller.'])[1]/preceding::span[5]</value>
      <webElementGuid>0f435b5a-fbbe-4354-9594-d27f5f31055f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/span/span</value>
      <webElementGuid>f7536f51-7072-47a2-a53f-70c233feebba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'exportsUndeliverable-cart' and (text() = ' Add to Cart ' or . = ' Add to Cart ')]</value>
      <webElementGuid>7cd41277-41e4-47e5-9428-1e2811732816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
