<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Quantity1</name>
   <tag></tag>
   <elementGuidId>4f42fd34-e676-4d4f-a302-53b6efa7c653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='a-autoid-0-announce']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-0-announce</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>87f5e308-0641-4c25-81ee-60423877c408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text a-declarative</value>
      <webElementGuid>065a06b8-2861-4619-9b0a-069bdf278ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-func-deps</name>
      <type>Main</type>
      <value>aui-da-a-dropdown-button</value>
      <webElementGuid>37f27ea8-097f-48d1-b2d4-0a8fa229054b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>0338baae-47f2-4222-b26b-cf1e2a6b4f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>118f7b21-e2c7-4d84-b1d4-d419edf9c115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-button</value>
      <webElementGuid>2de8d728-5b82-456f-9783-e0abe07ee43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>daea884c-a8ee-45fc-8548-e975306684a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>un4h31-k6fxyz-xqawyz-ndbaqv</value>
      <webElementGuid>ddcca6f2-27e6-4056-81ff-d7247bee2eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>199c0afd-fb5e-4df9-82e3-4c79af02c91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quantity:1 </value>
      <webElementGuid>1db0c120-c4b4-4f30-bf56-e87ee4d58869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0-announce&quot;)</value>
      <webElementGuid>171ac0c1-5384-4b4e-8e80-4605db8f152d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0-announce']</value>
      <webElementGuid>9905125b-7c02-4ece-bb51-c8d30b3ae840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/span</value>
      <webElementGuid>2a20667a-3757-484f-a648-93ce5b82d5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/following::span[3]</value>
      <webElementGuid>34dc1d06-7f28-4910-89dd-2bed18c0e9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only 20 left in stock - order soon.'])[1]/following::span[5]</value>
      <webElementGuid>ae28ae83-0e54-4c5a-a038-3da690c9f699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/preceding::span[3]</value>
      <webElementGuid>706ce141-3155-4463-aad6-fb992c1bc508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>14b86674-9f64-46cd-8507-fddc7dbc8a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'a-autoid-0-announce' and (text() = 'Quantity:1 ' or . = 'Quantity:1 ')]</value>
      <webElementGuid>0df9ce92-018c-4725-9a82-c7bc86c71b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
