<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_a-column a-span1 a-spacing-base a-span-last</name>
   <tag></tag>
   <elementGuidId>7c06f95e-4e36-4bf3-b82a-24cd8632880a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='profile-pick-actor-button-0']/a/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.a-column.a-span1.a-spacing-base.a-span-last</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7460020d-e070-48a7-96a6-b2442d152027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-column a-span1 a-spacing-base a-span-last</value>
      <webElementGuid>31839eae-8552-4e5b-b7b3-00de5bc078dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile-pick-actor-button-0&quot;)/a[@class=&quot;a-color-base a-link-normal linkStylingHover&quot;]/div[@class=&quot;a-row a-spacing-top-small a-grid-vertical-align a-grid-center a-ws-row&quot;]/div[@class=&quot;a-column a-span1 a-spacing-base a-span-last&quot;]</value>
      <webElementGuid>a01cfea5-8e96-4fb6-867a-7b9d6e9bb8bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='profile-pick-actor-button-0']/a/div/div[2]</value>
      <webElementGuid>9704bfb5-1151-46af-b27a-91f00f8956ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]</value>
      <webElementGuid>d2123f8d-9894-4e67-86cc-a26ddadf4436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
