<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to Cart</name>
   <tag></tag>
   <elementGuidId>d39bbdbc-7c53-47da-b93e-4505fe19f204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exportsUndeliverable-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='exportsUndeliverable-cart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>044ef662-22ee-4dee-bf44-25c513cf76df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exportsUndeliverable-cart</value>
      <webElementGuid>f41a43f1-1a03-4cdf-bb42-03f6850e90ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-disabled a-button-span12 a-button-primary a-button-icon</value>
      <webElementGuid>2825c5d0-5913-47fb-8402-0e2d488e435f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add to Cart </value>
      <webElementGuid>53b0868c-f88b-420b-ad3f-301d70e87400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exportsUndeliverable-cart&quot;)</value>
      <webElementGuid>e7d31c39-9dba-4bb3-8cb0-e2ec4c1d1c8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='exportsUndeliverable-cart']</value>
      <webElementGuid>05f0baeb-dc67-44e0-886a-3489ef4ddf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='exportsUndeliverable-popover']/span</value>
      <webElementGuid>ccb4b4f0-ce7a-4fb0-8902-9d8b57b7d2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/span/span</value>
      <webElementGuid>d6cc0a3f-9f24-4fac-abae-bceb2b5be032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'exportsUndeliverable-cart' and (text() = ' Add to Cart ' or . = ' Add to Cart ')]</value>
      <webElementGuid>d0d63845-e23b-4bd4-bc98-9c6c1cfb323e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
