<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_a-icon a-icon-checkbox</name>
   <tag></tag>
   <elementGuidId>6e8deedc-5d37-4fb0-a0e8-53e71d3dcd1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.a-icon.a-icon-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='p_n_feature_twenty_browse-bin/13054657011']/span/a/div/label/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0b087737-cdb9-4f99-9314-fd0824f1ef92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-checkbox</value>
      <webElementGuid>185d042e-5f1e-4051-8c73-7d54e632cd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p_n_feature_twenty_browse-bin/13054657011&quot;)/span[@class=&quot;a-list-item&quot;]/a[@class=&quot;a-link-normal s-navigation-item&quot;]/div[@class=&quot;a-checkbox a-checkbox-fancy s-navigation-checkbox aok-float-left&quot;]/label[1]/i[@class=&quot;a-icon a-icon-checkbox&quot;]</value>
      <webElementGuid>b2f7c5b5-b746-4766-b6f7-8eaf66bdd165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='p_n_feature_twenty_browse-bin/13054657011']/span/a/div/label/i</value>
      <webElementGuid>bb1a2828-6f1e-4240-bac8-43b318204e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/i</value>
      <webElementGuid>0ff55d29-dc7b-4ded-9f1c-2296cb17d386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
