<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Test_Suite_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0175981b-baa0-4e4b-9aea-7b0a1faac682</testSuiteGuid>
   <testCaseLink>
      <guid>f2c2d265-be92-431c-b846-c517b9b12529</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data_Driven_Testing/TC_Amazon_Excel_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cc5e1585-e1fb-4873-b19d-ee0f96023f44</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_DDT_Excel/Amazon_TestData_Excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cc5e1585-e1fb-4873-b19d-ee0f96023f44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Category_Item</value>
         <variableId>3de6d066-af38-451e-8c5e-e283ec564ebc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cc5e1585-e1fb-4873-b19d-ee0f96023f44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Product</value>
         <variableId>037d981a-ea12-4e20-b8cb-a7b429fcefaf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
